from __future__ import annotations

from pathlib import Path

import torch
from torch.export import ExportedProgram
from torch.fx import Node
from torch.fx.node import Argument


ALIAS_TARGETS = frozenset(
    {
        "aten._assert_tensor_metadata.default",
        "aten.clone.default",
        "aten.contiguous.default",
        "aten.detach.default",
        "aten.to.dtype",
        "aten.to.dtype_layout",
    }
)


KERNEL_TARGETS = frozenset(
    {
        "aten.add.Tensor",
        "aten.cat.default",
        "aten.cos.default",
        "aten.div.Tensor",
        "aten.embedding.default",
        "aten.gelu.default",
        "aten.linear.default",
        "aten.matmul.default",
        "aten.mean.dim",
        "aten.mul.Tensor",
        "aten.neg.default",
        "aten.permute.default",
        "aten.pow.Tensor_Scalar",
        "aten.repeat_interleave.self_int",
        "aten.reshape.default",
        "aten.rsqrt.default",
        "aten.scaled_dot_product_attention.default",
        "aten.select.int",
        "aten.silu.default",
        "aten.sin.default",
        "aten.slice.Tensor",
        "aten.sub.Tensor",
        "aten.sum.dim_IntList",
        "aten.transpose.int",
        "aten.unsqueeze.default",
        "aten.view.default",
    }
)


def export_one(
    name: str,
    module: torch.nn.Module,
    args: tuple[torch.Tensor, ...],
    *,
    output_dir: Path,
    kwargs: dict[str, torch.Tensor | tuple[torch.Tensor, ...] | None] | None = None,
) -> Path:
    program = torch.export.export(module, args, kwargs=kwargs, strict=False)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{name}.py"
    output_path.write_text(render_exported_program(program, function_name=name))
    return output_path


def render_exported_program(program: ExportedProgram, *, function_name: str) -> str:
    lines = [
        '"""Generated by torch2air.export. Do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        "from torch2air.export.builder import AirBuilder, KernelAttr",
        "",
        "",
        f"def {function_name}(builder: AirBuilder) -> None:",
    ]
    body = _render_body(program)
    if not body:
        lines.append("    return")
    else:
        lines.extend(body)
    lines.append("")
    return "\n".join(lines)


def _render_body(program: ExportedProgram) -> list[str]:
    lines: list[str] = []
    for node in program.graph_module.graph.nodes:
        if node.op == "placeholder":
            shape, dtype = _tensor_meta(node)
            lines.append(
                f"    builder.define_tensor({node.name!r}, shape={shape!r}, dtype={dtype!r})"
            )
            continue
        if node.op == "output":
            for name in _output_name_tuple(node):
                lines.append(f"    builder.mark_output({name!r})")
            continue
        if node.op != "call_function":
            raise RuntimeError(f"unsupported FX node op {node.op!r} on {node.name}")

        shape, dtype = _tensor_meta(node)
        lines.append(f"    builder.define_tensor({node.name!r}, shape={shape!r}, dtype={dtype!r})")
        target = str(node.target)
        if target in ALIAS_TARGETS:
            lines.append(_render_alias(node, target))
            continue
        if target not in KERNEL_TARGETS:
            raise RuntimeError(f"unsupported aten op {target} on {node.name}")
        lines.extend(_render_kernel_call(node, target))
    return lines


def _render_alias(node: Node, target: str) -> str:
    source = _node_arg_name(node, 0)
    return _render_emit_kernel(
        target,
        output=node.name,
        inputs=(source,),
        attrs=(("alias", "true"),),
    )


def _render_kernel_call(node: Node, target: str) -> list[str]:
    if target in {"aten.add.Tensor", "aten.sub.Tensor", "aten.mul.Tensor", "aten.div.Tensor"}:
        return [_render_emit_kernel(target, output=node.name, inputs=_arg_names(node, 0, 1))]
    if target in {
        "aten.cos.default",
        "aten.neg.default",
        "aten.rsqrt.default",
        "aten.silu.default",
        "aten.sin.default",
    }:
        return [_render_emit_kernel(target, output=node.name, inputs=(_node_arg_name(node, 0),))]
    if target == "aten.pow.Tensor_Scalar":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(("exponent", _literal_arg(node, 1)),),
            )
        ]
    if target == "aten.gelu.default":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(("approximate", _literal_arg(node, 1, default="none")),),
            )
        ]
    if target in {"aten.view.default", "aten.reshape.default"}:
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(("shape", _literal_arg(node, 1)),),
            )
        ]
    if target == "aten.unsqueeze.default":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(("dim", _literal_arg(node, 1)),),
            )
        ]
    if target == "aten.permute.default":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(("dims", _literal_arg(node, 1)),),
            )
        ]
    if target == "aten.transpose.int":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(("dim0", _literal_arg(node, 1)), ("dim1", _literal_arg(node, 2))),
            )
        ]
    if target in {"aten.mean.dim", "aten.sum.dim_IntList"}:
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(
                    ("dims", _literal_arg(node, 1)),
                    ("keepdim", _literal_arg(node, 2, default=False)),
                ),
            )
        ]
    if target == "aten.embedding.default":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0), _node_arg_name(node, 1)),
            )
        ]
    if target == "aten.linear.default":
        bias = _optional_node_arg_name(node, 2)
        inputs = (_node_arg_name(node, 0), _node_arg_name(node, 1))
        if bias is not None:
            inputs = (*inputs, bias)
        return [_render_emit_kernel(target, output=node.name, inputs=inputs)]
    if target == "aten.matmul.default":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0), _node_arg_name(node, 1)),
            )
        ]
    if target == "aten.cat.default":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=_node_arg_names(node, 0),
                attrs=(("dim", _literal_arg(node, 1, default=0)),),
            )
        ]
    if target == "aten.slice.Tensor":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(
                    ("dim", _literal_arg(node, 1)),
                    ("start", _literal_arg(node, 2)),
                    ("end", _literal_arg(node, 3)),
                    ("step", _literal_arg(node, 4, default=1)),
                ),
            )
        ]
    if target == "aten.select.int":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(("dim", _literal_arg(node, 1)), ("index", _literal_arg(node, 2))),
            )
        ]
    if target == "aten.repeat_interleave.self_int":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(_node_arg_name(node, 0),),
                attrs=(
                    ("repeats", _literal_arg(node, 1)),
                    ("dim", _literal_arg(node, 2, default=_kwarg_literal(node, "dim", None))),
                ),
            )
        ]
    if target == "aten.scaled_dot_product_attention.default":
        return [
            _render_emit_kernel(
                target,
                output=node.name,
                inputs=(
                    _node_arg_name(node, 0),
                    _node_arg_name(node, 1),
                    _node_arg_name(node, 2),
                ),
                attrs=(("is_causal", _sdpa_is_causal(node)),),
            )
        ]
    raise AssertionError(f"missing renderer for {target}")


def _render_emit_kernel(
    target: str,
    *,
    output: str,
    inputs: tuple[str, ...],
    attrs: tuple[tuple[str, str], ...] = (),
) -> str:
    attr_text = ""
    if attrs:
        attr_items = ", ".join(f"KernelAttr({name!r}, {value!r})" for name, value in attrs)
        if len(attrs) == 1:
            attr_items += ","
        attr_text = f", attrs=({attr_items})"
    return f"    builder.emit_kernel({target!r}, output={output!r}, inputs={inputs!r}{attr_text})"


def _arg_names(node: Node, *indexes: int) -> tuple[str, ...]:
    return tuple(_arg_name(node, index) for index in indexes)


def _arg_name(node: Node, index: int) -> str:
    arg = _arg(node, index)
    if isinstance(arg, Node):
        return arg.name
    return repr(arg)


def _node_arg_name(node: Node, index: int) -> str:
    arg = _arg(node, index)
    if isinstance(arg, Node):
        return arg.name
    raise RuntimeError(f"{node.name} argument {index} must be a tensor-producing node")


def _optional_node_arg_name(node: Node, index: int) -> str | None:
    if index >= len(node.args):
        return None
    arg = _arg(node, index)
    if arg is None:
        return None
    if isinstance(arg, Node):
        return arg.name
    raise RuntimeError(f"{node.name} argument {index} must be a tensor-producing node or None")


def _node_arg_names(node: Node, index: int) -> tuple[str, ...]:
    arg = _arg(node, index)
    if not isinstance(arg, (list, tuple)):
        raise RuntimeError(f"{node.name} argument {index} must be a list of tensor nodes")
    names: list[str] = []
    for item in arg:
        if not isinstance(item, Node):
            raise RuntimeError(f"{node.name} list argument {index} contains a non-node item")
        names.append(item.name)
    return tuple(names)


def _literal_arg(node: Node, index: int, *, default: bool | int | str | None = None) -> str:
    if index >= len(node.args):
        return repr(default)
    return repr(_arg(node, index))


def _kwarg_literal(node: Node, name: str, default: bool | int | str | None) -> str:
    value = node.kwargs.get(name, default)
    return repr(value)


def _sdpa_is_causal(node: Node) -> str:
    if len(node.args) >= 6:
        return repr(_arg(node, 5))
    return _kwarg_literal(node, "is_causal", False)


def _arg(node: Node, index: int) -> Argument:
    try:
        return node.args[index]
    except IndexError as exc:
        raise RuntimeError(f"{node.name} is missing argument {index}") from exc


def _output_name_tuple(node: Node) -> tuple[str, ...]:
    if not node.args:
        return ()
    output = node.args[0]
    if isinstance(output, Node):
        return (output.name,)
    if isinstance(output, (list, tuple)):
        return tuple(item.name for item in output if isinstance(item, Node))
    return ()


def _tensor_meta(node: Node) -> tuple[tuple[int, ...], str]:
    tensor_meta = node.meta.get("tensor_meta")
    shape_value = getattr(tensor_meta, "shape", ())
    dtype_value = getattr(tensor_meta, "dtype", "")
    return tuple(int(dim) for dim in shape_value), str(dtype_value).removeprefix("torch.")
