from __future__ import annotations

from pathlib import Path

import torch
from torch.export import ExportedProgram
from torch.fx import Node
from torch.fx.node import Argument


KERNEL_FUNCTIONS: dict[str, str] = {
    "aten.add.Tensor": "aten_add_tensor",
    "aten.cat.default": "aten_cat_default",
    "aten.cos.default": "aten_cos_default",
    "aten.div.Tensor": "aten_div_tensor",
    "aten.embedding.default": "aten_embedding_default",
    "aten.gelu.default": "aten_gelu_default",
    "aten.linear.default": "aten_linear_default",
    "aten.matmul.default": "aten_matmul_default",
    "aten.mean.dim": "aten_mean_dim",
    "aten.mul.Tensor": "aten_mul_tensor",
    "aten.neg.default": "aten_neg_default",
    "aten.permute.default": "aten_permute_default",
    "aten.pow.Tensor_Scalar": "aten_pow_tensor_scalar",
    "aten.repeat_interleave.self_int": "aten_repeat_interleave_self_int",
    "aten.reshape.default": "aten_reshape_default",
    "aten.rsqrt.default": "aten_rsqrt_default",
    "aten.scaled_dot_product_attention.default": "aten_scaled_dot_product_attention_default",
    "aten.select.int": "aten_select_int",
    "aten.silu.default": "aten_silu_default",
    "aten.sin.default": "aten_sin_default",
    "aten.slice.Tensor": "aten_slice_tensor",
    "aten.sub.Tensor": "aten_sub_tensor",
    "aten.sum.dim_IntList": "aten_sum_dim_int_list",
    "aten.transpose.int": "aten_transpose_int",
    "aten.unsqueeze.default": "aten_unsqueeze_default",
    "aten.view.default": "aten_view_default",
}


ALIAS_TARGETS = frozenset(
    {
        "aten._assert_tensor_metadata.default",
        "aten.clone.default",
        "aten.contiguous.default",
        "aten.detach.default",
        "aten.to.dtype",
        "aten.to.dtype_layout",
    }
)


def export_one(
    name: str,
    module: torch.nn.Module,
    args: tuple[torch.Tensor, ...],
    *,
    output_dir: Path,
    kwargs: dict[str, torch.Tensor | tuple[torch.Tensor, ...] | None] | None = None,
) -> Path:
    program = torch.export.export(module, args, kwargs=kwargs, strict=False)
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{name}.py"
    output_path.write_text(render_exported_program(program, function_name=name))
    return output_path


def render_exported_program(program: ExportedProgram, *, function_name: str) -> str:
    lines = [
        '"""Generated by torch2air.export. Do not edit."""',
        "",
        "from __future__ import annotations",
        "",
        "from torch2air.export import kernels",
        "from torch2air.export.builder import AirBuilder",
        "",
        "",
        f"def {function_name}(builder: AirBuilder) -> None:",
    ]
    body = _render_body(program)
    if not body:
        lines.append("    return")
    else:
        lines.extend(body)
    lines.append("")
    return "\n".join(lines)


def _render_body(program: ExportedProgram) -> list[str]:
    lines: list[str] = []
    for node in program.graph_module.graph.nodes:
        if node.op == "placeholder":
            lines.append(f"    # placeholder {node.name}")
            continue
        if node.op == "output":
            lines.append(f"    # output {_output_names(node)}")
            continue
        if node.op != "call_function":
            raise RuntimeError(f"unsupported FX node op {node.op!r} on {node.name}")

        target = str(node.target)
        if target in ALIAS_TARGETS:
            lines.append(_render_alias(node, target))
            continue
        function_name = KERNEL_FUNCTIONS.get(target)
        if function_name is None:
            raise RuntimeError(f"unsupported aten op {target} on {node.name}")
        lines.extend(_render_kernel_call(node, target, function_name))
    return lines


def _render_alias(node: Node, target: str) -> str:
    source = _node_arg_name(node, 0)
    return (
        f"    kernels.alias(builder, source={source!r}, output={node.name!r}, "
        f"target={target!r})"
    )


def _render_kernel_call(node: Node, target: str, function_name: str) -> list[str]:
    if target in {"aten.add.Tensor", "aten.sub.Tensor", "aten.mul.Tensor", "aten.div.Tensor"}:
        return [
            (
                f"    kernels.{function_name}(builder, lhs={_arg_name(node, 0)!r}, "
                f"rhs={_arg_name(node, 1)!r}, output={node.name!r})"
            )
        ]
    if target in {
        "aten.cos.default",
        "aten.neg.default",
        "aten.rsqrt.default",
        "aten.silu.default",
        "aten.sin.default",
    }:
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r})"
        ]
    if target == "aten.pow.Tensor_Scalar":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, exponent={_literal_arg(node, 1)!r})"
        ]
    if target == "aten.gelu.default":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, approximate={_literal_arg(node, 1, default='none')!r})"
        ]
    if target in {"aten.view.default", "aten.reshape.default"}:
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, shape={_literal_arg(node, 1)!r})"
        ]
    if target == "aten.unsqueeze.default":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, dim={_literal_arg(node, 1)!r})"
        ]
    if target == "aten.permute.default":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, dims={_literal_arg(node, 1)!r})"
        ]
    if target == "aten.transpose.int":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, dim0={_literal_arg(node, 1)!r}, "
            f"dim1={_literal_arg(node, 2)!r})"
        ]
    if target in {"aten.mean.dim", "aten.sum.dim_IntList"}:
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, dims={_literal_arg(node, 1)!r}, "
            f"keepdim={_literal_arg(node, 2, default=False)!r})"
        ]
    if target == "aten.embedding.default":
        return [
            f"    kernels.{function_name}(builder, weight={_node_arg_name(node, 0)!r}, "
            f"indices={_node_arg_name(node, 1)!r}, output={node.name!r})"
        ]
    if target == "aten.linear.default":
        bias = _optional_node_arg_name(node, 2)
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"weight={_node_arg_name(node, 1)!r}, bias={bias!r}, output={node.name!r})"
        ]
    if target == "aten.matmul.default":
        return [
            f"    kernels.{function_name}(builder, lhs={_node_arg_name(node, 0)!r}, "
            f"rhs={_node_arg_name(node, 1)!r}, output={node.name!r})"
        ]
    if target == "aten.cat.default":
        return [
            f"    kernels.{function_name}(builder, tensors={_node_arg_names(node, 0)!r}, "
            f"output={node.name!r}, dim={_literal_arg(node, 1, default=0)!r})"
        ]
    if target == "aten.slice.Tensor":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, dim={_literal_arg(node, 1)!r}, "
            f"start={_literal_arg(node, 2)!r}, end={_literal_arg(node, 3)!r}, "
            f"step={_literal_arg(node, 4, default=1)!r})"
        ]
    if target == "aten.select.int":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, dim={_literal_arg(node, 1)!r}, "
            f"index={_literal_arg(node, 2)!r})"
        ]
    if target == "aten.repeat_interleave.self_int":
        return [
            f"    kernels.{function_name}(builder, source={_node_arg_name(node, 0)!r}, "
            f"output={node.name!r}, repeats={_literal_arg(node, 1)!r}, "
            f"dim={_literal_arg(node, 2, default=_kwarg_literal(node, 'dim', None))!r})"
        ]
    if target == "aten.scaled_dot_product_attention.default":
        return [
            f"    kernels.{function_name}(builder, query={_node_arg_name(node, 0)!r}, "
            f"key={_node_arg_name(node, 1)!r}, value={_node_arg_name(node, 2)!r}, "
            f"output={node.name!r}, is_causal={_sdpa_is_causal(node)!r})"
        ]
    raise AssertionError(f"missing renderer for {target}")


def _arg_name(node: Node, index: int) -> str:
    arg = _arg(node, index)
    if isinstance(arg, Node):
        return arg.name
    return repr(arg)


def _node_arg_name(node: Node, index: int) -> str:
    arg = _arg(node, index)
    if isinstance(arg, Node):
        return arg.name
    raise RuntimeError(f"{node.name} argument {index} must be a tensor-producing node")


def _optional_node_arg_name(node: Node, index: int) -> str | None:
    if index >= len(node.args):
        return None
    arg = _arg(node, index)
    if arg is None:
        return None
    if isinstance(arg, Node):
        return arg.name
    raise RuntimeError(f"{node.name} argument {index} must be a tensor-producing node or None")


def _node_arg_names(node: Node, index: int) -> tuple[str, ...]:
    arg = _arg(node, index)
    if not isinstance(arg, (list, tuple)):
        raise RuntimeError(f"{node.name} argument {index} must be a list of tensor nodes")
    names: list[str] = []
    for item in arg:
        if not isinstance(item, Node):
            raise RuntimeError(f"{node.name} list argument {index} contains a non-node item")
        names.append(item.name)
    return tuple(names)


def _literal_arg(node: Node, index: int, *, default: bool | int | str | None = None) -> str:
    if index >= len(node.args):
        return repr(default)
    return repr(_arg(node, index))


def _kwarg_literal(node: Node, name: str, default: bool | int | str | None) -> str:
    value = node.kwargs.get(name, default)
    return repr(value)


def _sdpa_is_causal(node: Node) -> str:
    if len(node.args) >= 6:
        return repr(_arg(node, 5))
    return _kwarg_literal(node, "is_causal", False)


def _arg(node: Node, index: int) -> Argument:
    try:
        return node.args[index]
    except IndexError as exc:
        raise RuntimeError(f"{node.name} is missing argument {index}") from exc


def _output_names(node: Node) -> str:
    if not node.args:
        return "()"
    output = node.args[0]
    if isinstance(output, Node):
        return output.name
    if isinstance(output, (list, tuple)):
        names = [item.name for item in output if isinstance(item, Node)]
        return repr(tuple(names))
    return repr(output)
