from __future__ import annotations

from torch.export import ExportedProgram
from torch.export.graph_signature import InputKind


def render_reference_module(*, model_id: str, reference_functions: list[str]) -> str:
    body = "\n\n\n".join(reference_functions).rstrip()
    return f'''# Generated by models.quantized_qwen3.export. Do not edit.
from __future__ import annotations

import numpy as np
import torch
from transformers import AutoModelForCausalLM


DEFAULT_MODEL_ID = {model_id!r}
ReferenceInput = np.ndarray | torch.Tensor
ReferenceOutput = dict[str, torch.Tensor]

_MODEL: torch.nn.Module | None = None


def load_model(model_id: str = DEFAULT_MODEL_ID) -> torch.nn.Module:
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        local_files_only=True,
        dtype=torch.float32,
    )
    set_model(model)
    return model


def set_model(model: torch.nn.Module) -> None:
    global _MODEL
    _MODEL = model.to(device="cuda", dtype=torch.float32).eval()


def clear_model() -> None:
    global _MODEL
    _MODEL = None


def get_model() -> torch.nn.Module:
    if _MODEL is None:
        return load_model()
    return _MODEL


class _EmbedTokensInputLayerNorm(torch.nn.Module):
    def __init__(self, root: torch.nn.Module) -> None:
        super().__init__()
        self.embed_tokens = root.model.embed_tokens
        self.input_layernorm = root.model.layers[0].input_layernorm

    def forward(self, input_ids: torch.Tensor) -> torch.Tensor:
        return self.input_layernorm(self.embed_tokens(input_ids))


def _arg(value: ReferenceInput) -> torch.Tensor:
    if isinstance(value, torch.Tensor):
        return value.detach().to(device="cuda")
    return torch.as_tensor(np.ascontiguousarray(value), device="cuda")


def _execute_module(
    module: torch.nn.Module,
    *,
    inputs: dict[str, ReferenceInput],
    output_bindings: dict[str, str],
) -> ReferenceOutput:
    kwargs = {{name: _arg(value) for name, value in inputs.items()}}
    with torch.no_grad():
        output = module(**kwargs)
    if isinstance(output, tuple):
        values = output
    else:
        values = (output,)
    if len(values) != len(output_bindings):
        raise RuntimeError(
            f"reference returned {{len(values)}} outputs, expected {{len(output_bindings)}}"
        )
    return {{name: value.to(torch.float32) for name, value in zip(output_bindings, values, strict=True)}}


{body}
'''


def render_exported_reference_function(
    ep: ExportedProgram,
    *,
    name: str,
    module_expr: str,
    input_bindings: dict[str, str] | None = None,
    output_bindings: dict[str, str] | None = None,
) -> str:
    if input_bindings is None:
        input_bindings = {
            spec.arg.name: spec.arg.name
            for spec in ep.graph_signature.input_specs
            if spec.kind == InputKind.USER_INPUT
        }
    if output_bindings is None:
        output_bindings = {
            spec.arg.name: spec.arg.name
            for spec in ep.graph_signature.output_specs
            if spec.arg is not None
        }
    params = ",\n    ".join(f"{name}: ReferenceInput" for name in input_bindings)
    if params:
        params += ",\n    "
    inputs_source = ", ".join(f"{key!r}: {value}" for key, value in input_bindings.items())
    return f'''def run_{name}(
    *,
    {params}model: torch.nn.Module | None = None,
) -> ReferenceOutput:
    root = get_model() if model is None else model
    return _execute_module(
        {module_expr},
        inputs={{{inputs_source}}},
        output_bindings={output_bindings!r},
    )'''
