from __future__ import annotations

from dataclasses import dataclass

import torch


@dataclass(frozen=True)
class TensorType:
    shape: tuple[int, ...]
    dtype: torch.dtype

    @property
    def mlir(self) -> str:
        shape_text = "x".join(str(dim) for dim in self.shape)
        return f"tensor<{shape_text}x{torch_dtype_to_mlir(self.dtype)}>"


def torch_dtype_to_mlir(dtype: torch.dtype) -> str:
    mapping = {
        torch.float32: "f32",
        torch.float16: "f16",
        torch.bfloat16: "bf16",
        torch.int32: "i32",
        torch.int64: "i64",
        torch.int8: "i8",
        torch.uint8: "ui8",
    }
    try:
        return mapping[dtype]
    except KeyError as exc:
        raise ValueError(f"unsupported dtype for MLIR export: {dtype}") from exc


def zero_constant_for(dtype: torch.dtype) -> str:
    if dtype in {torch.float32, torch.float16, torch.bfloat16}:
        return f"arith.constant 0.000000e+00 : {torch_dtype_to_mlir(dtype)}"
    if dtype in {torch.int32, torch.int64, torch.int8, torch.uint8}:
        return f"arith.constant 0 : {torch_dtype_to_mlir(dtype)}"
    raise ValueError(f"unsupported dtype for linalg.fill zero: {dtype}")


def tensor_type_from_torch(tensor: torch.Tensor) -> TensorType:
    return TensorType(shape=tuple(int(dim) for dim in tensor.shape), dtype=tensor.dtype)


def render_linalg_matmul(
    *,
    function_name: str,
    lhs: TensorType,
    rhs: TensorType,
    result: TensorType,
) -> str:
    if len(lhs.shape) != 2 or len(rhs.shape) != 2 or len(result.shape) != 2:
        raise ValueError("only rank-2 matmul is supported")
    if lhs.shape[1] != rhs.shape[0]:
        raise ValueError(f"incompatible matmul shapes: {lhs.shape} x {rhs.shape}")
    if result.shape != (lhs.shape[0], rhs.shape[1]):
        raise ValueError(f"unexpected matmul result shape: {result.shape}")

    result_scalar = torch_dtype_to_mlir(result.dtype)
    zero_op = zero_constant_for(result.dtype)
    return f"""// Generated by torch2air.
// Frontend shape: {lhs.mlir} x {rhs.mlir} -> {result.mlir}

func.func @{function_name}(%lhs: {lhs.mlir}, %rhs: {rhs.mlir}) -> {result.mlir} {{
  %zero = {zero_op}
  %empty = tensor.empty() : {result.mlir}
  %init = linalg.fill ins(%zero : {result_scalar}) outs(%empty : {result.mlir}) -> {result.mlir}
  %result = linalg.matmul
      ins(%lhs, %rhs : {lhs.mlir}, {rhs.mlir})
      outs(%init : {result.mlir}) -> {result.mlir}
  return %result : {result.mlir}
}}
"""
